SportComplex/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from rest_framework import routers
from application.views import TrainingViewSet
from django.views.i18n import JavaScriptCatalog

router = routers.DefaultRouter()
router.register(r'^trainings', TrainingViewSet)

urlpatterns = [
    re_path(r'^', include('application.urls')),
    re_path(r'^api/v1/', include(router.urls)),
]

urlpatterns += i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    prefix_default_language=False
)

application/urls.py
from django.urls import re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .forms import UserLoginForm
from .views import CustomResetPasswordView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'application'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^profile/?$', views.profile, name='users-profile'),
    re_path(r'^login/',
        auth_views.LoginView.as_view(
            template_name="registration/login.html",
            authentication_form=UserLoginForm
            ),
        name='login'),
    re_path(r'^password_reset/', 
        CustomResetPasswordView.as_view(), 
        name='password_reset'),
    re_path(r'^logout/',
        auth_views.LogoutView.as_view(template_name="registration/logged_out.html"),
        name='logout'),
    re_path(r'^password_reset_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html")
        ),
    re_path(r'^schedule/?$', login_required(views.schedule_page),
        name='schedule'),
    re_path(r'^schedule/(?P<training_id>[0-9]+)$', views.schedule_get,
        name='schedule_get'),
    re_path(r'^schedule/delete$', login_required(views.schedule_delete),
        name='schedule_delete'),
    re_path(r'^schedule/update$', login_required(views.schedule_update),
        name='schedule_update'),
    
    re_path(r'^managing/?$', login_required(views.managing),
        name='managing'),
    
    re_path(r'^accounts/(?P<user_id>[0-9]+)$', login_required(views.account_get),
        name='account_get'),
    re_path(r'^accounts/delete$', login_required(views.account_delete),
        name='account_delete'),
    re_path(r'^accounts/update$', login_required(views.account_update),
        name='account_update'),
    
    re_path(r'^abonements/(?P<abonement_id>[0-9]+)$', login_required(views.abonement_get),
        name='abonement_get'),
    re_path(r'^abonements/delete$', login_required(views.abonement_delete),
        name='abonement_delete'),
    re_path(r'^abonements/update$', login_required(views.abonement_update),
        name='abonement_update'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

application/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import CustomUser, Training, Abonement
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import classonlymethod
from django.views.decorators.cache import cache_control
from django.contrib.auth.views import PasswordResetView
from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import *
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from rest_framework import permissions, viewsets
from .decorators import has_permission, has_one_permission
from django.http import JsonResponse
from django.contrib.auth.models import Group
from datetime import datetime, timedelta

from .serializers import *



def index(request):
    return render(request, 'application/mainpage.html', {})

def buff(request):
    return render(request, 'application/buff.html', {})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required
def profile(request):
    return render(request, 'application/profile.html')


class CustomResetPasswordView(SuccessMessageMixin, PasswordResetView):
    form_class = CustomPassResetForm
    template_name="registration/password_reset_form.html"
    email_template_name = 'registration/password_reset_email.html'
    subject_template_name = 'password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = 'password_reset_done'


class TrainingViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Training.objects.all()#.order_by('training_date')
    serializer_class = TrainingSerializer
    permission_classes = [permissions.IsAuthenticated]


def is_in_group(user, group_name):
    return user.groups.filter(name=group_name).exists()

@login_required
@has_one_permission('admin', 'trainer', 'client')
def schedule_page(request):
    #print(training_serializer.data)
    current_user = request.user
    if (request.method == 'GET'):
        if (is_in_group(current_user, 'admin')):
            training_sessions = Training.objects.all()
            training_serializer = TrainingSerializer(training_sessions, many=True)
            add_form = TrainingSessionForm(request.POST)
            add_form.setPrefix("add_")
            upd_form = TrainingSessionForm()
            upd_form.setPrefix("upd_")
            return render(request, "application/schedule.html", {'training_serializer': training_serializer.data,
                                                            'add_form': add_form,
                                                            'upd_form': upd_form})
        if (is_in_group(current_user, 'trainer')):
            training_sessions = Training.objects.filter(training_leader__in = [current_user.user_id])
            training_serializer = TrainingSerializer(training_sessions, many=True)
            add_form = TrainingSessionForm(request.POST)
            add_form.setPrefix("add_")
            upd_form = TrainingSessionForm()
            upd_form.setPrefix("upd_")
            return render(request, "application/schedule.html", {'training_serializer': training_serializer.data,
                                                            'add_form': add_form,
                                                            'upd_form': upd_form})
        elif (is_in_group(current_user, 'client')):
            training_sessions = Training.objects.filter(clients__in = [current_user.user_id])
            #print(Training.objects.filter(clients__in = [4]), current_user.user_id)
            training_serializer = TrainingSerializer(training_sessions, many=True)
            return render(request, "application/schedule.html", {'training_serializer': training_serializer.data})
    elif (request.method == 'POST'):
        temp_data = TrainingSessionForm(request.POST)
        if temp_data.is_valid():
            print(temp_data.fields)
            if (temp_data.data.get('clients')):
                new_data = temp_data.save(commit=False)
                new_data.training_leader_id = request.user.user_id
                #print(new_data)
                new_data.save()
                temp_data.save_m2m()
                print('saved')
                return redirect('application:schedule')
            else:
                redirect('application:schedule')
        else:
            return redirect('application:schedule')
    


@login_required
@has_one_permission('admin', 'trainer')
def schedule_delete(request):
    id = request.POST.get('training_id')
    schedule_record = get_object_or_404(Training, pk=id)
    context = {'schedule_record': schedule_record}    
    output = schedule_record.delete()
    print(output)
    messages.success(request,  'The schedule_record has been deleted successfully.')
    return redirect('application:schedule')

@login_required
@has_one_permission('admin', 'trainer')
def schedule_get(request, training_id):
    current_user = request.user
    #training_id = request.GET.get('training_id')
    training = Training.objects.get(training_id=training_id)
    cl = training.clients.all()
    print(cl)
    clients = list()
    for i in cl:
        clients.append(str(i.user_id))
    data = {
        'training_id': training.training_id,
        'training_date': training.training_date,
        'training_type': training.training_type.training_type_id,
        'clients': clients
    }
    return JsonResponse(data)


@login_required
@has_one_permission('admin', 'trainer')
def schedule_update(request):
    if request.method == 'POST':
        #print(request.__dict__)
        instance = get_object_or_404(Training, training_id=request.POST.get('training_id'))
        instance_id = instance.training_leader_id
        temp_data = TrainingSessionForm(request.POST, instance=instance)
        print(instance.training_leader)
        if (instance and temp_data.is_valid()):
            if (temp_data.data.get('clients')):
                new_data = temp_data.save(commit=False)
                new_data.training_leader_id = instance_id
                new_data.save()
                temp_data.save_m2m()
                return redirect('application:schedule')
        else:
            print(temp_data.errors)

        return redirect('application:schedule')
    else:
        return redirect('application:schedule')


@login_required
@has_permission('admin')
def managing(request):
    #print(training_serializer.data)
    current_user = request.user
    if (request.method == 'GET'):
        accounts_list = CustomUser.objects.filter(groups__name='client')
        abonements_list = Abonement.objects.all()
        accounts_serializer = CustomUserSerializer(accounts_list, many=True)
        #abonements_serializer = CustomUserSerializer(accounts_list, many=True)
        add_client_form = ClientForm(request.POST)
        add_client_form.setPrefix("add_")
        upd_client_form = ClientForm(edition=True)
        upd_client_form.setPrefix("upd_")
        add_abonement_form = AbonementForm(request.POST)
        add_abonement_form.setPrefix("add_")
        upd_abonement_form = AbonementForm(edition=True)
        upd_abonement_form.setPrefix("upd_")
        #upd_form.setEditionMode(True)
        return render(request, "application/managing.html", {'accounts_serializer': accounts_serializer.data,
                                                            'abonements_list': abonements_list,
                                                            'add_client_form': add_client_form,
                                                            'upd_client_form': upd_client_form,
                                                            'add_abonement_form': add_abonement_form,
                                                            'upd_abonement_form': upd_abonement_form})
    elif (request.method == 'POST'):
        if (request.POST.__contains__('add_client')):
            temp_data = ClientForm(data=request.POST)
            if temp_data.is_valid():
                print(temp_data.fields)
                new_data = temp_data.save(commit=False)
                new_data.set_password(
                    temp_data.cleaned_data["password"]
                )
                new_data.is_staff = True
                new_data.is_active = True
                #print(new_data)
                new_data.save()
                client_group = Group.objects.get(name='client') 
                new_data.groups.add(client_group)
                return redirect('application:managing')
            else:
                print(temp_data.errors)
                return redirect('application:managing')
        elif (request.POST.__contains__('add_abonement')):
            temp_data = AbonementForm(data=request.POST)
            if temp_data.is_valid():
                print(temp_data.fields)
                new_data = temp_data.save(commit=False)
                print(new_data.opened)
                new_data.expires = new_data.opened + timedelta(new_data.abonement_type.duration_in_days)
                #print(new_data)
                new_data.save()
                return redirect('application:managing')
            else:
                print(temp_data.errors)
                return redirect('application:managing')


@login_required
@has_permission('admin')
def account_delete(request):
    id = request.POST.get('user_id')
    print(id)
    account_item = get_object_or_404(CustomUser.objects.filter(groups__name='client'), pk=id)
    context = {'account_item': account_item}  

application/templates/base_template.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	{% load i18n %}
    <title>{% translate "Sport Complex" %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
	  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
  </head>
  <body>
    <ul class="sidebar-nav">
        <header class="p-3 mb-3 border-bottom">
          <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
              <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
              </a>
      
              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 link-secondary">{% translate "Home" %}</a></li>
                {% load user_tags %}
                {% if user.is_authenticated %}
                  <li><a href="/schedule" class="nav-link px-2 link-dark">{% translate "Schedule" %}</a></li>
                  {% if user.is_authenticated and request.user|has_group:"admin" %}
                    <li><a href="/managing" class="nav-link px-2 link-dark">{% translate "Managing" %}</a></li>
                  {% endif %}
                {% endif %}
              </ul>
              {% if user.is_authenticated %}
              <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                  {% if user.avatar %}
                    <img src="{{user.avatar.url}}" alt="avatar" class="rounded-circle" width="32" height="32">
                  {% else %}
                    <img src="{% static 'images/default_avatar.jpg' %}" alt="avatar" class="rounded-circle" width="32" height="32">
                  {% endif %}
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                  <li><a class="dropdown-item" href="/profile">{% translate "Profile" %}</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'application:logout'%}?next={{request.path}}">{% translate "Sign out" %}</a></li>
                </ul>
              </div>
              {% else %}
                <div class="col-md-3 text-end">
                  <a href="{% url 'application:login'%}?next={{request.path}}">{% translate "Login" %}</a>
                </div>
              {% endif %}
            </div>
          </div>
        </header>
    </ul>
    {% block bodyblock %}
	  {% endblock %}
    <footer class="text-light mt-3">
      <div class="container">
        <div class="row">
          <div class="col text-center">
            <div class="phone p-3">{% translate "Телефон:" %} +7 (800) 900-10-20</div>
          </div>
          <div class="col-6 text-center">
            <div class="address p-3">{% translate "Address: Saint-Petersburg, Bolshaya Morkaya st., 67" %}</div>
          </div>
          <div class="col text-center">
            <div class="email p-3">{% translate "E-mail:" %} sportcomplex@gmail.com</div>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>